blog:
  localGithub: F:/github/note
  localGitee: F:/gitee/notebook
  imgPrefix: https://raw.githubusercontent.com/doudio/note/master/
  githubBlog: F:/github/doudio.github.io
  targetDir: ${blog.githubBlog}/_posts
